favicon: null
cta:
  bucket: null
  version: null
  domain: null
opengraph:
  image: null
  type: null
  appId: null
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
purpose: []
color:
  saturation: 0.7556391
  brandStrength: 0
  rhythmicContrast: 0
  brandColors:
    - '#535145'
    - '#D7EBF6'
    - '#9C9D95'
    - '#090909'
    - '#EF4E56'
  lightness: 0
typography_spectrum: 0.25025
layout_spectrum: 1
analytics:
  twitter: null
  google: null
  facebook: null
name: Deb
