favicon: null
name: Deb
opengraph:
  image: null
  type: null
  appId: null
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
purpose: []
color:
  saturation: 0.6875
  brandStrength: 0.4435074566863477
  lightness: 0.2678179922513664
  brandColors:
    - '#A5A4A9'
    - '#1B222A'
    - '#F5BCA8'
    - '#050100'
    - '#83625B'
  rhythmicContrast: 0.7094867303967476
typography_spectrum: 0.25025
cta:
  bucket: null
  version: null
  domain: null
layout_spectrum: 0.11565
analytics:
  twitter: null
  google: null
  facebook: null
