name: Deb
favicon: null
layout_spectrum: 0.84147
typography_spectrum: 0.080835364991799
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#090708'
    - '#dccfd6'
    - '#bba58e'
    - '#55443d'
    - '#c6e271'
  brandStrength: 0.4435074566863477
  lightness: 0.2678179922513664
  saturation: 0.6823557468596846
  rhythmicContrast: 0.7094867303967476
purpose: []
